version: '3'

services:
  app:
    container_name: ${CONTAINER_NAME}
    restart: unless-stopped
    build: ./docker
    image: blogbiere-dev
    volumes:
      - ${PWD}/www:/var/www
    ports:
      - ${CONTAINER_PORT}:80
    networks:
      - blogbiere
    env_file:
      - .env

  mysql:
    container_name: ${CONTAINER_MYSQL}
    restart: unless-stopped
    image: mariadb
    networks: 
      - blogbiere
    env_file:
      - .env

  mailcatcher:
    container_name: mailcatcher
    restart: unless-stopped
    image: tophfr/mailcatcher
    ports:
      - 1080:80
    networks: 
      - blogbiere

networks: 
  blogbiere:
    driver: bridge